### ISSUE TITLE
trailing empty field not included in output

### ISSUE THREAD

**Issue by uvtc** [zenlor/janet-csv#1]
Given file foo.csv containing:

~~~
color,size,shape
red,9,round
green,3,
blue,,square
~~~

When I run

~~~clojure
(import csv)

(def aoa (csv/parse (slurp "foo.csv")))
(pp aoa)
~~~

I'm expecting:

~~~python
@[@["color" "size" "shape"] @["red" "9" "round"] @["green" "3" ""] @["blue" "" "square"]]
~~~

(that is, expecting empty string after "green" "3" (like how it's there after "blue"))

but I get:

~~~python
@[@["color" "size" "shape"] @["red" "9" "round"] @["green" "3"] @["blue" "" "square"]]
~~~

This is using Janet 1.15.3.

**Comment by zenlor** [comment]
ah good catch :) CSV is so simple and yet it has far too many edge cases. I'll see if I get some time these days to look into it

**Comment by uvtc** [comment]
Awesome! Thanks, Lorenzo.
