### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tionis** [zenlor/janet-csv#3]
I'd like to integrate the grammar into my own project but you don't seem to have a license, under which would you like to distribute the code?

Also would you be open to integrate this into spork? Might be a good fit.

**Comment by zenlor** [comment]
I just added a license to the project, thanks for opening this issue!

**Comment by tionis** [comment]
Thanks!

**Comment by tionis** [comment]
@zenlor I just wanted to check again, regarding integrating this code into spork.
Would you be ok with me opening a pull request to https://github.com/janet-lang/spork based on your code?

**Comment by zenlor** [comment]
@tionis yes, definitely, use the code as you see fit. If you need another license feel free to ask, ISC should be pretty permissive.

**Comment by tionis** [comment]
Sure, thanks!
